# TODO: Fill in discipline definition

name: security
display_name: TODO
acronym: SECR
icon: Code
color: "#808080"
description: TODO
conventions: TODO
skills: []
system_prompt: TODO
image_prompt:
  positive: "TODO"
  negative: "TODO"
